### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by axd1x8a** [ASMfreaK/aiotinydb#13]
Latest version in the master is 2.0.0, but on PyPI is still 1.2.2, is there a new release planned?

**Comment by d-k-bo** [comment]
You are absolutely right, I never released the current version to PyPI since some licensing questions were not resolved. I'll look into solving these issues as soon as possible. In the meantime you can use this version by installing it directly from this repository: `pip install git+https://github.com/aiotinydb/aiotinydb.git`.

**Comment by axd1x8a** [comment]
Yes, I already did that, but I would like to keep track of versions, and not specify commits.

**Comment by d-k-bo** [comment]
Version 2.0.0 is now available on [PyPI](https://pypi.org/project/aiotinydb/)!
